import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const vendors=[
{name:"Mangomint",base:82,cost:"From ~$120/location + users",why:["small-to-growing teams","memberships & inventory","HIPAA-oriented forms/charting"],clinical:2,multi:3,budget:2},
{name:"AestheticsPro",base:80,cost:"Published plans from ~$160/mo",why:["aesthetics-specific workflows","photos & patient records","growing practices"],clinical:4,multi:3,budget:2},
{name:"PatientNow",base:77,cost:"Custom quote",why:["medical-aesthetics workflows","patient engagement","clinical + business stack"],clinical:5,multi:4,budget:4},
{name:"Phorest",base:75,cost:"Custom quote",why:["3+ staff","marketing & memberships","multi-location operations"],clinical:3,multi:4,budget:3},
{name:"Vagaro",base:72,cost:"Lower-cost entry tier",why:["small practices","booking & memberships","simple operations"],clinical:1,multi:2,budget:1},
{name:"Zenoti",base:70,cost:"Custom quote",why:["complex clinical workflows","multi-location management","advanced operations"],clinical:5,multi:5,budget:5}];
function score(v,f){let s=v.base;if(f.providers<=2){if(["Vagaro","Mangomint","AestheticsPro"].includes(v.name))s+=8;if(v.name==="Zenoti")s-=10}if(f.providers>=6){if(["Zenoti","PatientNow","Phorest"].includes(v.name))s+=9;if(v.name==="Vagaro")s-=8}if(f.locations>=2)s+=(v.multi-2)*5;if(f.clinical==="advanced")s+=(v.clinical-2)*5;if(f.clinical==="basic"&&v.clinical>=5)s-=6;if(f.budget==="low")s-=(v.budget-1)*4;if(f.memberships&&v.why.some(x=>x.includes("membership")))s+=4;return Math.max(35,Math.min(97,s))}
function App(){const[f,setF]=useState({providers:3,locations:1,clinical:"basic",memberships:true,budget:"mid"});const[done,setDone]=useState(false);const results=vendors.map(v=>({...v,score:score(v,f)})).sort((a,b)=>b.score-a.score).slice(0,3);return <main><header><span className="eyebrow">INDEPENDENT SOFTWARE FIT CHECK</span><h1>Which med spa software actually fits your practice?</h1><p>Answer five questions. Get a shortlist based on practice size, clinical complexity and operating needs — not a generic “top 10” list.</p></header><section className="card"><div className="grid"><label>Providers<input type="number" min="1" max="50" value={f.providers} onChange={e=>setF({...f,providers:+e.target.value})}/></label><label>Locations<input type="number" min="1" max="20" value={f.locations} onChange={e=>setF({...f,locations:+e.target.value})}/></label><label>Clinical workflow<select value={f.clinical} onChange={e=>setF({...f,clinical:e.target.value})}><option value="basic">Basic aesthetics / booking</option><option value="advanced">Advanced medical / injectables</option></select></label><label>Monthly software budget<select value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}><option value="low">Under $200</option><option value="mid">$200–$500</option><option value="high">$500+</option></select></label><label className="check"><input type="checkbox" checked={f.memberships} onChange={e=>setF({...f,memberships:e.target.checked})}/> Memberships / packages matter</label></div><button onClick={()=>setDone(true)}>Find my best fit →</button></section>{done&&<section><h2>Your best-fit shortlist</h2><p className="muted">For a {f.providers}-provider, {f.locations}-location practice. Scores are decision-support estimates, not vendor endorsements.</p><div className="results">{results.map((r,i)=><article className="result" key={r.name}><div><small>#{i+1} MATCH</small><h3>{r.name}</h3></div><strong>{r.score}% fit</strong><p>{r.cost}</p><ul>{r.why.map(x=><li key={x}>{x}</li>)}</ul><p className="explain">{r.score>85?"Strong fit for the needs you selected.":"Worth comparing, but verify pricing and workflow details in a demo."}</p></article>)}</div></section>}<section className="note"><b>How this works</b><p>Recommendations use transparent rules for team size, locations, clinical complexity, budget and workflow. Pricing changes frequently; verify current quotes with each vendor before buying.</p></section></main>}createRoot(document.getElementById("root")).render(<App/>);