import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
export const vendors=[
{name:"Mangomint",base:72,cost:"$120/location + $10/user",strengths:["HIPAA-capable forms & charting with BAA","memberships, inventory & integrations","free onboarding/data transfer; cancel anytime"],clinical:3,multi:3,budget:2,crm:4,eprescribe:false,advancedClinical:false},
{name:"AestheticsPro",base:70,cost:"$160 Pro-Plus; $285 Executive; $350 Enterprise",strengths:["med-spa EMR, photos & 500+ forms","e-prescribing and inventory","Executive/Enterprise support multi-location"],clinical:5,multi:4,budget:2,crm:3,eprescribe:true,advancedClinical:true},
{name:"PatientNow",base:68,cost:"Custom quote",strengths:["aesthetic EMR, photos & inventory","memberships, marketing & practice management","free onboarding/migration; no long-term contract"],clinical:5,multi:4,budget:4,crm:5,eprescribe:false,advancedClinical:true},
{name:"Phorest",base:68,cost:"Custom quote",strengths:["HIPAA charting, consent & before/after photos","marketing, memberships & inventory","centralized multi-location reporting"],clinical:3,multi:5,budget:3,crm:5,eprescribe:false,advancedClinical:false},
{name:"Vagaro",base:68,cost:"US base from $23.99/mo + calendars/add-ons",strengths:["HIPAA EMR, SOAP notes & before/after photos","e-prescribing, memberships & inventory","multi-location management available"],clinical:4,multi:4,budget:1,crm:3,eprescribe:true,advancedClinical:true},
{name:"Zenoti",base:64,cost:"Custom quote",strengths:["complex clinical workflows","multi-location management","advanced operations"],clinical:5,multi:5,budget:5,crm:5,eprescribe:true,advancedClinical:true}];
export function hardFit(v,f){const misses=[];if(f.eprescribe&&!v.eprescribe)misses.push("e-prescribing");if(f.clinical==="advanced"&&!v.advancedClinical)misses.push("advanced clinical workflow");return {eligible:misses.length===0,misses}}
export function score(v,f){const gate=hardFit(v,f);let s=v.base;if(!gate.eligible)s-=35;
if(f.providers<=2){if(["Vagaro","Mangomint","AestheticsPro"].includes(v.name))s+=10;if(["Zenoti","PatientNow"].includes(v.name))s-=10}
else if(f.providers<=5){if(["Mangomint","AestheticsPro","Phorest","PatientNow"].includes(v.name))s+=7}
else{if(["Zenoti","PatientNow","Phorest"].includes(v.name))s+=12;if(v.name==="Vagaro")s-=10}
if(f.locations>=2)s+=(v.multi-2)*6;if(f.locations>=3&&v.multi>=4)s+=5;
if(f.providers>=10&&f.locations>=3){if(v.name==="Zenoti")s+=16;if(v.name==="PatientNow")s+=10;if(v.name==="Phorest")s+=7;if(v.name==="AestheticsPro")s-=10;if(v.name==="Mangomint")s-=8;if(v.name==="Vagaro")s-=14}
if(f.clinical==="advanced")s+=(v.clinical-2)*6;else if(v.clinical>=5)s-=7;
if(f.budget==="low")s-=(v.budget-1)*6;if(f.budget==="high"&&v.budget>=4)s+=3;
if(f.memberships&&["Mangomint","Phorest","Vagaro","Zenoti"].includes(v.name))s+=4;
if(f.marketing)s+=(v.crm-3)*3;if(f.inventory&&["Mangomint","AestheticsPro","Zenoti","Phorest"].includes(v.name))s+=3;
if(f.eprescribe&&v.eprescribe)s+=6;
if(f.photos&&["AestheticsPro","PatientNow","Zenoti"].includes(v.name))s+=4;
if(f.integrations&&["PatientNow","Zenoti","Phorest","Mangomint"].includes(v.name))s+=3;
if(f.appointments==="high"&&["Zenoti","PatientNow","Phorest"].includes(v.name))s+=5;
if(f.switching&&["Mangomint","PatientNow","Phorest"].includes(v.name))s+=2;
if(f.switching&&f.migration==="important"){if(["PatientNow","Phorest"].includes(v.name))s+=7;if(v.name==="Zenoti"&&f.locations>=3)s+=5;if(["Mangomint","Vagaro"].includes(v.name))s+=3}
if(f.support==="important"){if(v.name==="Phorest")s+=6;if(v.name==="PatientNow")s+=5}
if(f.flexibility==="important"){if(v.name==="PatientNow")s+=6;if(v.name==="Mangomint")s+=5}
return Math.max(30,Math.min(94,s))}
export function fitLabel(score){if(score>=82)return "Strong fit";if(score>=70)return "Good fit";return "Possible fit"}
function bestFor(r,f){const map={
Vagaro:f.providers<=2?"a simple, lower-cost start":"teams prioritizing straightforward booking and operations",
Mangomint:f.providers<=2?"a small practice that wants room to grow":"growing teams that care about polished day-to-day operations",
AestheticsPro:f.clinical==="advanced"?"aesthetics-specific clinical workflows":"practices wanting more med-spa-specific workflows",
PatientNow:"medical aesthetics practices combining clinical and business workflows",
Phorest:f.locations>=2?"growing or multi-location practices with strong marketing needs":"established teams focused on retention and marketing",
Zenoti:f.locations>=2?"complex multi-location operations":"larger practices with advanced operational and clinical needs"};return map[r.name]}
function tradeoff(r,f){const map={
Vagaro:f.clinical==="advanced"?"may be too lightweight for advanced clinical workflows":"may feel limiting as operational complexity grows",
Mangomint:f.clinical==="advanced"?"not the strongest match when deep medical workflows drive the decision":"cost can rise with users and locations; verify the full quote",
AestheticsPro:f.budget==="low"?"can stretch a sub-$200 budget depending on the plan you need":"verify user/provider limits and the exact plan needed",
PatientNow:f.providers<=2?"may be more platform than a small, simple practice needs":"custom pricing makes total cost harder to compare upfront",
Phorest:f.providers<=2?"may be more than a solo or very small practice needs":"verify whether its clinical depth matches your exact treatments",
Zenoti:f.providers<=2?"likely overkill for a simple single-provider setup":"enterprise-style complexity and custom pricing deserve a careful demo"};return map[r.name]}
function reason(r,f){const a=[];if(f.providers<=2&&["Vagaro","Mangomint","AestheticsPro"].includes(r.name))a.push("fits a small team without forcing enterprise complexity");if(f.providers>=6&&["Zenoti","PatientNow","Phorest"].includes(r.name))a.push("better aligned with a larger operating team");if(f.locations>=2&&r.multi>=4)a.push("stronger multi-location fit");if(f.clinical==="advanced"&&r.clinical>=4)a.push("supports a more clinical workflow");if(f.budget==="low"&&r.budget<=2)a.push("closer to your stated budget");if(f.marketing&&r.crm>=4)a.push("stronger CRM/marketing fit");if(f.eprescribe&&r.eprescribe)a.push("includes the required e-prescribing capability");if(f.photos&&["AestheticsPro","PatientNow","Zenoti"].includes(r.name))a.push("fits before/after photo workflows");if(f.appointments==="high"&&["Zenoti","PatientNow","Phorest"].includes(r.name))a.push("better suited to higher appointment volume");if(f.switching&&f.migration==="important"&&["PatientNow","Phorest","Zenoti"].includes(r.name))a.push("stronger documented migration support");if(f.support==="important"&&["PatientNow","Phorest"].includes(r.name))a.push("documented onboarding and human support");if(f.flexibility==="important"&&r.name==="PatientNow")a.push("no long-term contract");return a.slice(0,4)}
export function rankVendors(f){return vendors.map(v=>({...v,score:score(v,f),gate:hardFit(v,f)})).sort((a,b)=>(b.gate.eligible-a.gate.eligible)||(b.score-a.score))}
function App(){const[f,setF]=useState({providers:3,locations:1,clinical:"basic",appointments:"mid",memberships:true,marketing:false,inventory:false,eprescribe:false,photos:false,integrations:false,switching:false,migration:"normal",support:"normal",flexibility:"normal",budget:"mid"});const[done,setDone]=useState(false);const results=rankVendors(f).map(r=>({...r,reasons:reason(r,f)})).slice(0,3);
return <main><header><span className="eyebrow">INDEPENDENT SOFTWARE FIT CHECK</span><h1>Which med spa software actually fits your practice?</h1><p>Tell us how your practice operates. We’ll narrow six common platforms to the three worth investigating first.</p></header>
<section className="card"><div className="grid"><label>Providers<input type="number" min="1" max="50" value={f.providers} onChange={e=>setF({...f,providers:Math.max(1,+e.target.value)})}/></label><label>Locations<input type="number" min="1" max="20" value={f.locations} onChange={e=>setF({...f,locations:Math.max(1,+e.target.value)})}/></label><label>Clinical workflow<select value={f.clinical} onChange={e=>setF({...f,clinical:e.target.value})}><option value="basic">Booking + basic aesthetics</option><option value="advanced">Injectables / advanced medical</option></select></label><label>Monthly software budget<select value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}><option value="low">Under $200</option><option value="mid">$200–$500</option><option value="high">$500+</option></select></label>
<label>Appointments / month<select value={f.appointments} onChange={e=>setF({...f,appointments:e.target.value})}><option value="low">Under 200</option><option value="mid">200–750</option><option value="high">750+</option></select></label><label>Current situation<select value={f.switching?"switching":"new"} onChange={e=>setF({...f,switching:e.target.value==="switching"})}><option value="new">Choosing a first system</option><option value="switching">Switching from another system</option></select></label>{f.switching&&<label>Migration help<select value={f.migration} onChange={e=>setF({...f,migration:e.target.value})}><option value="normal">Nice to have</option><option value="important">Very important</option></select></label>}<label>Onboarding & human support<select value={f.support} onChange={e=>setF({...f,support:e.target.value})}><option value="normal">Standard is fine</option><option value="important">Very important</option></select></label><label>Contract flexibility<select value={f.flexibility} onChange={e=>setF({...f,flexibility:e.target.value})}><option value="normal">Not a priority</option><option value="important">Avoid long commitments</option></select></label><label className="check"><input type="checkbox" checked={f.memberships} onChange={e=>setF({...f,memberships:e.target.checked})}/> Memberships / packages</label><label className="check"><input type="checkbox" checked={f.marketing} onChange={e=>setF({...f,marketing:e.target.checked})}/> CRM / marketing automation matters</label><label className="check"><input type="checkbox" checked={f.inventory} onChange={e=>setF({...f,inventory:e.target.checked})}/> Inventory tracking matters</label><label className="check"><input type="checkbox" checked={f.photos} onChange={e=>setF({...f,photos:e.target.checked})}/> Before / after photos matter</label><label className="check"><input type="checkbox" checked={f.eprescribe} onChange={e=>setF({...f,eprescribe:e.target.checked})}/> E-prescribing / deeper medical workflow</label><label className="check"><input type="checkbox" checked={f.integrations} onChange={e=>setF({...f,integrations:e.target.checked})}/> Integrations with other tools matter</label></div><button type="button" onClick={()=>{setDone(true);setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth",block:"start"}),50)}}>Find my best fit →</button></section>
{done&&<section id="results"><h2>Your best-fit shortlist</h2><p className="muted">Profile: {f.providers} providers · {f.locations} location{f.locations>1?"s":""} · {f.clinical==="advanced"?"advanced clinical":"basic aesthetic"} workflow · {f.appointments==="low"?"<200":f.appointments==="mid"?"200–750":"750+"} appointments/month.</p><div className="results">{results.map((r,i)=><article className="result" key={r.name}><small>#{i+1} MATCH</small><h3>{r.name}</h3><strong>{r.gate.eligible?fitLabel(r.score):"Does not meet a required need"}</strong><p>{r.cost}</p>{!r.gate.eligible&&<p className="muted">Missing: {r.gate.misses.join(", ")}.</p>}<div className="decision"><b>Best if</b><p>{bestFor(r,f)}.</p><b>Watch out</b><p>{tradeoff(r,f)}.</p></div>{r.reasons.length>0&&<><b>Why it matched</b><ul>{r.reasons.map(x=><li key={x}>{x}</li>)}</ul></>}<b>Worth verifying</b><ul>{r.strengths.map(x=><li key={x}>{x}</li>)}</ul><p className="explain">Pricing, contracts and feature availability can change. Verify the exact workflow and total cost in a vendor demo.</p></article>)}</div></section>}
<section className="note"><b>What the score means</b><p>Recommendations are ranked using transparent decision-support rules based on practice size, locations, clinical complexity, budget and selected workflows. Fit labels are directional, not percentages or guarantees. It is not a clinical recommendation or vendor endorsement.</p></section></main>}
createRoot(document.getElementById("root")).render(<App/>);